# Generated by Django 4.0.4 on 2022-05-02 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.ManyToManyField(related_name='question_posta', to=settings.AUTH_USER_MODEL),
        ),
    ]
